type(1.2 + 3.8)
type(10 // 100)
type(1 >= 0)
type('Hello World' == 'Hello World')
type(not 'Chainer' != 'Tutorial')
type(all([True, True, False]))
type(any([True, True, False]))
type(abs(-3))
type(2//0)
