print(type(1.2 + 3.8))
print(type(10 // 100))
print(type(1 >= 0))
print(type('Hello World' == 'Hello World')
print(type(not 'Chainer' != 'Tutorial')
print(type(all([True, True, False]) )
print(type(any([True, True, False]) )
print(type(abs(-3) )
print(type(2 // 0)
